# Generated by Django 6.0.2 on 2026-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العمل')),
                ('description', models.TextField(verbose_name='وصف العمل')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='صورة العمل')),
                ('url', models.URLField(blank=True, verbose_name='رابط المشروع (إن وجد)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
