# Generated by Django 6.0.2 on 2026-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='رابط الكود (GitHub - إن وجد)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='نشر المشروع؟ (إلغاء التحديد سيخفيه من الموقع)'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, verbose_name='رابط المشروع الحي (Live)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200, verbose_name='التقنيات المستخدمة (مثل: Django, HTML)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio_images/', verbose_name='صورة المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المشروع'),
        ),
    ]
