# Generated by Django 5.1.2 on 2026-02-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_project_options_remove_project_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default=1, upload_to='portfolio_images/', verbose_name='الصورة الرئيسية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='رابط الكود (GitHub)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='نشر المشروع؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200, verbose_name='التقنيات المستخدمة'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_gallery/', verbose_name='صورة إضافية')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='وصف مختصر للصورة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': 'معرض صور المشروع',
            },
        ),
    ]
