# Generated by Django 5.1.2 on 2026-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_project_image_project_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio_images/', verbose_name='صورة المشروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='رابط الكود (GitHub - إن وجد)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='نشر المشروع؟ (إلغاء التحديد سيخفيه من الموقع)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200, verbose_name='التقنيات المستخدمة (مثل: Django, HTML)'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
