# Generated by Django 5.1.2 on 2026-05-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_contactmessage_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='وصف المشروع (مختصر)'),
        ),
        migrations.CreateModel(
            name='ProjectParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='محتوى الفقرة')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='الترتيب (اختياري)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='store.project')),
            ],
            options={
                'verbose_name': 'فقرة المشروع',
                'verbose_name_plural': 'فقرات المشروع',
                'ordering': ['order', 'id'],
            },
        ),
    ]
