# Generated by Django 6.0.6 on 2026-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_project_description_projectparagraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='وصف المشروع بالإنجليزي (مختصر)'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='اكتب رقم لترتيب المشروع. المشروع ذو الرقم الأصغر يظهر أولاً.', verbose_name='ترتيب العرض (الأصغر يظهر أولاً)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان المشروع (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='projectparagraph',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='محتوى الفقرة (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectparagraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
